package com.mycompany.report;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MUEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private long facilityId;
   private java.lang.Long userId;
   private java.lang.Long encounterId;
   private java.lang.String eventType;

   @Override
   public String toString() {
      return "MUEvent{" +
              "facilityId=" + facilityId +
              ", userId=" + userId +
              ", encounterId=" + encounterId +
              ", eventType='" + eventType + '\'' +
              ", eventDate=" + eventDate +
              ", encounterDate=" + encounterDate +
              '}';
   }

   private java.util.Date eventDate;
   private java.util.Date encounterDate;

   public MUEvent()
   {
   }

   public long getFacilityId()
   {
      return this.facilityId;
   }

   public void setFacilityId(long facilityId)
   {
      this.facilityId = facilityId;
   }

   public java.lang.Long getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.Long userId)
   {
      this.userId = userId;
   }

   public java.lang.Long getEncounterId()
   {
      return this.encounterId;
   }

   public void setEncounterId(java.lang.Long encounterId)
   {
      this.encounterId = encounterId;
   }

   public java.lang.String getEventType()
   {
      return this.eventType;
   }

   public void setEventType(java.lang.String eventType)
   {
      this.eventType = eventType;
   }

   public java.util.Date getEventDate()
   {
      return this.eventDate;
   }

   public void setEventDate(java.util.Date eventDate)
   {
      this.eventDate = eventDate;
   }

   public java.util.Date getEncounterDate()
   {
      return this.encounterDate;
   }

   public void setEncounterDate(java.util.Date encounterDate)
   {
      this.encounterDate = encounterDate;
   }

   public MUEvent(long facilityId, java.lang.Long userId,
         java.lang.Long encounterId, java.lang.String eventType,
         java.util.Date eventDate, java.util.Date encounterDate)
   {
      this.facilityId = facilityId;
      this.userId = userId;
      this.encounterId = encounterId;
      this.eventType = eventType;
      this.eventDate = eventDate;
      this.encounterDate = encounterDate;
   }

}